### ISSUE TITLE
이벤트 버블링

### ISSUE THREAD

**Issue by SsongCh94** [Final-Project-Team11/Meer_catlender_FE#126]
# 이벤트 버블링

## 상황

- `UploadedOne`에서 호출된 `Modal`에 `Modal` 을 닫는 `closeModal` 이라는 함수가 있다.
    - `closeModal`, `Modal` 나오는 조건
        
        ```tsx
        const closeModal = () => {
            setModalOpen(false);
            console.log('test');
          };
        ```
        
        ```tsx
        {modalOpen && (
                <Modal closeModal={closeModal}>
                  <UploadedDetail
                    data={data}
                    isLoading={isLoading}
                    type={type}
                    closeModal={closeModal}
                  />
                </Modal>
              )}
        ```
        
    - `Modal` 컴포넌트의 백그라운드 클릭 코드
        
        ```tsx
        <StModalBackground
                background={background}
                onClick={() => closeModal()}
              ></StModalBackground>
        ```
        
- `Modal` 은 `UploadedDetail` 을 `children`으로 받아서 모달에서 보여준다.
- `UploadedDetail`에서 `props`로 `closeModal`을 받아서 `button` 의 `onClick`에 넣어주었지만 `closeModal` 안의 `console.log(’test’)` 는 출력되지만 `modalOpen state`가 변경되지 않아서 모달이 닫히지 않는다.
- 마찬가지로 모달의 백그라운드를 클릭해도 똑같은 현상이 발생한다.

## 이벤트 버블링 - Event Bubbling

이벤트 버블링은 특정 화면 요소에서 이벤트가 발생했을 때 해당 이벤트가 더 상위의 화면 요소들로 전달되어 가는 특성을 의미한다. 

![image](https://user-images.githubusercontent.com/122278657/233428841-b58f5dc6-1aa2-4fce-9b70-4a3e3cbb3c4f.png)

### 위의 이벤트 버블링 에서 문제 발생

- 기존 UploadedOne 컴포넌트 코드
    
    ```tsx
    return (
          <UI.StUploadedFileBlock key={file.eventId} onClick={modalOpenHandler}>
    					{modalOpen && (
    		        <Modal closeModal={closeModal}>
    		          <UploadedDetail
    		            data={data}
    		            isLoading={isLoading}
    		            type={type}
    		            closeModal={closeModal}
    		          />
    		        </Modal>
    			      )}
            <UI.StNameDateBlock>
              <UI.StContentSpan>😵‍💫 | {file.userName}</UI.StContentSpan>
              <UI.StDateSpan className="date"> {file.enrollDay}</UI.StDateSpan>
            </UI.StNameDateBlock>
            <UI.StContentSpan>📎 | {file.fileName}</UI.StContentSpan>
          </UI.StUploadedFileBlock>
      );
    ```
    
- 기존 UploadedOne 컴포넌트의 최상위 div요소인 StUploadedFileBlock 는 onClick 이벤트로 modalOpne state를 true로 만든다.
    - Modal 컴포넌트는 최상위 div 안에서 호출되었다.
        - 모달을 닫는 closeModal 함수를 가지고있는 button 요소는 Modal 안에 있다.
- button에서 생긴 onClick 이벤트는 이벤트 버블링에 따라 동시에 최상위 div의 onClick 이벤트도 발동시킨다.

### 왜 button 의 closeModal 안에있는 콘솔 ‘test’ 는 출력되면서 왜 콘솔에 modalOpen의 변경사항은 찍히지 않는가.

- setState는 비동기이므로 closeModal 에서 setModalOpen(false) 가 발동하고 최상위 div의 setModalOpen(true) 가 비동기로 발동되는데 결과로 true 만 반환하게 된다.
- 동작 순서
    - button 에서 onClick 이벤트 발생 → 콘솔에 ‘test’ 출력 → 상위 div로  onClick 이벤트 전달, 동작 → button의 onClick이벤트인 closeModal이 비동기로 동작 → 상위 div의 openModal도 비동기로 동작 → 비동기로 실행된 결과값인 true만 돌아오게됨.
    - modalOpen 의 상태 업데이트가 일어나기 전에 비동기로 false로 만들고 다시 true로 만들어서 내보냈으니 true인 결과만 보게 된다.

## onMouseDown 은 동작했던 이유

- onMouseDown 은 마우스를 눌렀다 떼는 동작이 아닌 누르는 동작에서 바로 반응하여 동작한다.
- 마우스가 버튼을 누르는 순간 이미 modalOpen은 false로 바뀌며 모달이 사라졌고, 이벤트가 등록된 요소의 위에서 마우스를 눌렀다가 떼야 동작하는 onClick 이벤트는 마우스를 떼는 동작을 할 수가 없으니 동작하지 않는다.
- mouseDown 을 하는 순간 Modal이 사라졌기 때문.

## 이벤트 버블링 방지 방법

```tsx
<UI.CloseButton *onClick*={closeModal}>닫기</UI.CloseButton>
```

위의 기존 코드를 아래와 같이 e.stopPropagation 를 사용한 코드로 바꾸면 상위 요소로 이벤트가 전파되는 이벤트 버블링을 방지할 수 있다.

```tsx
const closeModal = (event) => {
event.stopPropagation();
setModalOpen(false);
};

<UI.CloseButton *onClick*={closeModal}>닫기</UI.CloseButton>
```

**Comment by SsongCh94** [comment]
#121 에서 발생한 이슈

**Comment by chanw9503** [comment]
event.stopPropagation() 라는방법이 있었군요! 버블링 관련해서 해결이 되서 다행입니다. 
저희가 같이봤을 때, useState(false) 이후 렌더링 되기 전에 버블링으로 인해 useState(true)까지 일어나면서
결국 상태값 변화가 없다고 인식이 되버리는 문제가 발생했던거같습니다. 

그와 관련된 로그를 다음에는 같이 붙여주시면 다른분들이 이해할때 도움이 될거같습니다. 고생하셨습니다.
